language: python
python: 3.6
before_install:
  - sudo apt-get update
  - sudo apt-get install -y hunspell hunspell-fr-comprehensive
install:
  - pip install pospell
script:
  - pospell --glob '[a-k]*.po' -p dict -l fr
  - make CPYTHON_CLONE=/tmp/cpython/ BRANCH=3.7
